In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4,5,6,67])

In [3]:
v1



array([ 1,  2,  3,  4,  5,  6, 67])

In [4]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
m2 = np.matrix([[1,2,3],[4,5,6]])

In [9]:
m2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [12]:
t1 = np.array([ [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]] ])

In [13]:
t1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
v1.shape,m1.shape,m2.shape,t1.shape

((7,), (3, 3), (2, 3), (2, 2, 3))

In [15]:
m3 = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
m4 = np.array([[5,5,5],[6,6,6],[7,7,7],[8,8,8]])
m3.shape,m4.shape

((4, 3), (4, 3))

In [16]:
m5 = m3+m4

In [17]:
m5

array([[ 6,  6,  6],
       [ 8,  8,  8],
       [10, 10, 10],
       [12, 12, 12]])

In [18]:
m5+5

array([[11, 11, 11],
       [13, 13, 13],
       [15, 15, 15],
       [17, 17, 17]])

In [19]:
# Exercise 2.2

In [20]:
m5.shape

(4, 3)

In [21]:
m6 = np.reshape(m5,[3,4])

In [22]:
m5

array([[ 6,  6,  6],
       [ 8,  8,  8],
       [10, 10, 10],
       [12, 12, 12]])

In [23]:
m6

array([[ 6,  6,  6,  8],
       [ 8,  8, 10, 10],
       [10, 12, 12, 12]])

In [28]:
np.reshape(m6,[2,2,3]),'\n',np.reshape(m6,[2,2,3]).shape

(array([[[ 6,  6,  6],
         [ 8,  8,  8]],
 
        [[10, 10, 10],
         [12, 12, 12]]]), '\n', (2, 2, 3))

In [29]:
np.reshape(m6,[12])

array([ 6,  6,  6,  8,  8,  8, 10, 10, 10, 12, 12, 12])

In [30]:
m7 = np.matrix([1,2,3,4,5,6,7,8,9,10,11,12])

In [35]:
m7 = np.reshape(m7,[4,3])
m7,m7.shape

(matrix([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]), (4, 3))

In [37]:
m8 = m7.T
m8,m8.shape

(matrix([[ 1,  4,  7, 10],
         [ 2,  5,  8, 11],
         [ 3,  6,  9, 12]]), (3, 4))

In [38]:
np.reshape(m7,[3,4])==m8

matrix([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]])

In [39]:
#Ex 2.3

In [40]:
m9 = np.matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m10 = m9+1
m9,m10

(matrix([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]), matrix([[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10],
         [11, 12, 13]]))

In [41]:
m9.dot(m10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [42]:
m9.T.dot(m10)

matrix([[188, 210, 232],
        [214, 240, 266],
        [240, 270, 300]])

In [43]:
m10.dot(m9.T)

matrix([[ 20,  47,  74, 101],
        [ 38,  92, 146, 200],
        [ 56, 137, 218, 299],
        [ 74, 182, 290, 398]])

In [44]:
np.reshape(m9,[3,4]).dot(m10)

matrix([[ 80,  90, 100],
        [184, 210, 236],
        [288, 330, 372]])

In [47]:
m9.dot(np.reshape(m10,[3,4]))

matrix([[ 44,  50,  56,  62],
        [ 98, 113, 128, 143],
        [152, 176, 200, 224],
        [206, 239, 272, 305]])

In [50]:
#Checking multiplication of 3D tensor
t2 = np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])
t2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
t2.shape

(2, 2, 2)

In [52]:
t3 = t2+2

In [53]:
t3, t3.shape

(array([[[ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10]]]), (2, 2, 2))

In [54]:
t2.dot(t3)

array([[[[ 13,  16],
         [ 25,  28]],

        [[ 29,  36],
         [ 57,  64]]],


       [[[ 45,  56],
         [ 89, 100]],

        [[ 61,  76],
         [121, 136]]]])

In [59]:
t4 = np.array([ [[1,2],[3,4],[3,4]], [[5,6],[7,8],[7,8]] , [[5,6],[7,8],[7,8]] ])
t4, t4.shape

(array([[[1, 2],
         [3, 4],
         [3, 4]],
 
        [[5, 6],
         [7, 8],
         [7, 8]],
 
        [[5, 6],
         [7, 8],
         [7, 8]]]), (3, 3, 2))

In [60]:
t2.dot(t4)

ValueError: shapes (2,2,2) and (3,3,2) not aligned: 2 (dim 2) != 3 (dim 1)

In [63]:
t4.dot(t2)

array([[[[  7,  10],
         [ 19,  22]],

        [[ 15,  22],
         [ 43,  50]],

        [[ 15,  22],
         [ 43,  50]]],


       [[[ 23,  34],
         [ 67,  78]],

        [[ 31,  46],
         [ 91, 106]],

        [[ 31,  46],
         [ 91, 106]]],


       [[[ 23,  34],
         [ 67,  78]],

        [[ 31,  46],
         [ 91, 106]],

        [[ 31,  46],
         [ 91, 106]]]])

In [61]:
t3.dot(t4)

ValueError: shapes (2,2,2) and (3,3,2) not aligned: 2 (dim 2) != 3 (dim 1)

In [64]:
t4.dot(t2).shape

(3, 3, 2, 2)

In [65]:
#Activity

In [66]:
import pandas as pd
%matplotlib inline



In [69]:
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00468/online_shoppers_intention.csv')


In [70]:
#From chap1, we need to do:
# get X,Y
# Convert weekend to binary
# one hot visitortype,month,os, browser,traffictype,region
# train test split

X = data.drop('Revenue',axis=1)
Y = data.Revenue

X['is_weekend'] = X.Weekend.apply(lambda element:1 if element== True else 0)
X.drop('Weekend',axis=1,inplace=True)

def onehotcolumn(dataset,columnname):
    dummies = pd.get_dummies(dataset[columnname],prefix=columnname)
    colToDrop = dummies.mean().idxmin()
    print('dropping col',colToDrop)
    dummies.drop(colToDrop,axis=1,inplace=True)
    dataset = pd.concat([dataset,dummies],axis=1)
    dataset.drop(columnname,axis=1,inplace=True)
    return dataset
    
X=onehotcolumn(X,'VisitorType')
X=onehotcolumn(X,'Month')
X=onehotcolumn(X,'OperatingSystems')
X=onehotcolumn(X,'Browser')
X=onehotcolumn(X,'TrafficType')
X=onehotcolumn(X,'Region')

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape


dropping col VisitorType_Other
dropping col Month_Feb
dropping col OperatingSystems_5
dropping col Browser_9
dropping col TrafficType_12
dropping col Region_5


((9864, 68), (2466, 68), (9864,), (2466,))

In [78]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation


In [79]:
model = Sequential()

In [81]:
model.add(Dense(1,input_dim=68))
model.add(Activation('tanh'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [83]:
history = model.fit(x=X,y=Y,epochs=10,batch_size=32,validation_split=0.2,shuffle=False)

Epoch 1/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 2/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 3/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 4/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 5/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 6/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 7/10
309/309 [==============================] - 0s 1ms/step - loss: 2.2112 - accuracy: 0.8567 - val_loss: 3.0900 - val_accuracy: 0.7997
Epoch 